### ISSUE TITLE
Site Freezes at 100% Upload Speed Test (2 SP)

### ISSUE THREAD

**Issue by khutchison** [Hack4Eugene/SpeedUpAmerica#190] opened 2019-08-16 20:08 UTC
**Describe the bug**
I noticed that the speed test stopped at 100% while I was investigating another issue at home. 

**To Reproduce**
Take internet speed test using browser location (haven't checked others). I've attached the console logs and a screenshot. I tried to reload the site and do the test again and the issue recurred. 

**Desktop (please complete the following information):**
 - OS & Version: Ubuntu 19.04
 - Browser: Firefox 

Note that otherwise the site works; explore the data and the map work fine. 
![stuckat100](https://user-images.githubusercontent.com/6693683/63195240-f13b5b00-c026-11e9-843e-be67a94b7279.png)
![console_logs](https://user-images.githubusercontent.com/6693683/63195242-f13b5b00-c026-11e9-8aa6-d600cde1a223.png)

**Comment by khutchison** [comment] 2019-08-16 20:11
I tried again on Google chrome and it works there, so it seems to be specific to Firefox.

**Comment by ryanrolds** [comment] 2019-08-17 20:09
It's not specific to Firefox. The issue is M-Lab serves a mix of v4 and v5 NDT servers. v5 exposes a race condition in the protocol and requires an update to the client to mitigate. They just merged changes (https://github.com/m-lab/ndt-server/pull/172) to their current NDT5 (v5) JS client. We need to switch out current implementation using the updated client. 

I'm setting this ticket to 2SP and marking it urgent.

**Comment by JCoulter85** [comment] 2019-08-20 19:19
Looking into the issue. Thank you for the detailed write up.

**Comment by ryanrolds** [comment] 2019-08-22 16:22
It's already fixed.

**Closed** 2019-08-22 16:22 UTC
Labels: bug, urgent
