### ISSUE TITLE
submitting speed test very slow

### ISSUE THREAD

**Issue by nohorse** [Hack4Eugene/SpeedUpAmerica#125] opened 2019-06-13 16:28 UTC
Taking the test the second time I thought maybe it crashed.  After the speed test I was stuck on a "data submitted" popup for about 20-40 seconds before it took me to the map.

**Comment by ryanrolds** [comment] 2019-06-13 16:34
When you took the test, what options did you select the first and the second time?

**Comment by ryanrolds** [comment] 2019-06-13 16:46
I just tried it to reproduce. I'm there are definietely some state issues related to using the back button. 

I checked the logs and all of the submission times for `/submissions` is under 15ms. I suspect this is related to the Geolocation API taking a while to return a location, I recall we adjusted the submission path to wait until we get a location before it submits, but I would need to confirm.

@nohorse What is the device? Does it have a real GPS receiver?

**Comment by nohorse** [comment] 2019-06-13 16:51
this was my work laptop HP elietebook on a wifi connection.  No GPS radio and prolly a fusion sensor that is falling back on wifi or IP for location.

**Comment by ryanrolds** [comment] 2019-06-13 16:55
Can you attempt to reproduce with the dev tools open to the network tab and preserve logs turned on? If you see the issue please screenshot the entires surrounding the POST to `/submissions` and check the console output for errors. Thank you.

Also, what were options you selected when took the test the first and second time?

**Comment by ryanrolds** [comment] 2019-06-13 16:56
Browser and version and OS details would also be helpful, normal bug reporting stuff.

**Comment by nohorse** [comment] 2019-06-13 16:57
I'd love to dig deeper but I'm getting on a plane for Chatanooga.  I'll give it one last test and take some screen-grabs that might help a bit.

**Comment by nohorse** [comment] 2019-06-13 17:01
![image](https://user-images.githubusercontent.com/311063/59452037-b9fbc400-8dc1-11e9-817d-dd88e8b67203.png)
![image](https://user-images.githubusercontent.com/311063/59452099-d992ec80-8dc1-11e9-8afa-7f2f7b15aee4.png)
![image](https://user-images.githubusercontent.com/311063/59452155-f4fdf780-8dc1-11e9-9870-1ef616c35466.png)
![image](https://user-images.githubusercontent.com/311063/59452193-0515d700-8dc2-11e9-92e2-0a4f159a924d.png)

hope that helps.  it was faster this time.  might be unable-to-recreate if you don;t get more reports.

**Comment by ryanrolds** [comment] 2019-06-13 19:12
@nohorse Please provide Browser and OS information.

**Comment by nohorse** [comment] 2019-06-13 19:23
Chrome on windows

Sent from my BlackBerry - the most secure mobile device

**Comment by ryanrolds** [comment] 2019-06-13 19:25
What versions?

**Comment by ryanrolds** [comment] 2019-06-13 19:26
Closing ticket because I'm tired of playing detail collection games with Mark. He knows how to submit proper bug reports.

**Closed** 2019-06-13 19:25 UTC
