### ISSUE TITLE
Add Comcast and Century Link to Provider List

### ISSUE THREAD

**Issue by csjoblom** [Hack4Eugene/SpeedUpAmerica#47] opened 2019-04-28 04:54 UTC
Do the addy of the things please

**Comment by noahbrenner** [comment] 2019-04-28 05:23
I'm seeing both of those providers listed in this file: https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/db/seeds.rb
Is there a different place these additions are needed?

**Comment by ryanrolds** [comment] 2019-04-29 18:42
It looks like the list in the "residential" speed test path isn't pulling from the list in the seeds.

**Comment by ryanrolds** [comment] 2019-04-29 18:42
This is higher priority.

**Comment by noahbrenner** [comment] 2019-04-29 21:10
On Sunday, I was digging through the codebase to find where the ISP list in the View Map page drop-down was coming from. I've come up blank so far. At the time I checked, this is the list displayed in that drop-down:

```
All
Time Warner
Toast.net
ATT
Shelby Broadband
Windstream
Broadband view
Inside Connect Cable
Aero
Lighttower
Level 3
MegaPath
Birch
Verizon
Us Signal
Earthlink
Bluegrass.net
Iglou
Silica Broadband
T-Mobile
Sprint
Cricket Wireless
Boost Moile
US Cellular
Other
XS Media
```

Various ISPs are listed in different files, some with more and some with fewer than this list, and frequently just mismatched. There was no single collection that aligned with the above list (ignoring "All" or course). My current theory is that it's being dynamically generated from the DB in some way, though even that explanation only works with some filtering I haven't figured out at this point: The DB *does* include Comcast and Century Link and many more that aren't shown, and even includes test results specifying them (not just entries in the providers table).

I first thought I'd found it here, but it didn't line up: app/helpers/home_helper.rb

Then I followed this path:

* app/views/submissions/_filters.html.erb:21 - which queries data from:
    * app/helpers/submissions_helper.rb:65 - which uses a class from:
        * app/models/provider_statistic.rb

But I didn't know where to go from there. It looks like it's building a SQL query, but I'm not familiar with Ruby and I don't know what "applications" is referring to, since I didn't see either a table or column in the DB with that name (maybe I just missed it).

This kind of rabbit hole on a presumably simple issue is another reason on the pile that makes me think it would be good to just prioritize re-writing the front end and making our own decisions about how to populate that list.

**Comment by benanamen** [comment] 2019-04-30 02:10
> On Sunday, I was digging through the codebase to find where the ISP list in the View Map page drop-down was coming from. I've come up blank so far. 

@noahbrenner , that list is pulled from the database table named "provider_statistics". The DB is not properly normalized so that does not help things. FYI, this is @Kevin from Slack.

**Comment by noahbrenner** [comment] 2019-04-30 03:32
Awesome, thanks @benanamen! I'll try to find some time in the next couple days to take a look and get that updated.

**Comment by noahbrenner** [comment] 2019-04-30 16:31
Alright, that works to update the lists (Residential & Mobile) of ISPs in the survey! I'm thinking we should ad XS Media as well. I'll also alphabetize the lists, since I don't see any logic to the order currently.

Does anyone have a list of the ISPs available in Lane County (maybe @mattsayre)? Since we're just focusing locally at this stage, it may be better UX to eliminate locally-irrelevant options. Here are the current lists (including additions and alphabetized):

### Residential

* ATT
* Aero
* Birch
* Bluegrasss.net
* Broadband view
* Century Link
* Comcast
* Earthlink
* Iglou
* Inside Connect Cable
* Level 3
* Lighttower
* MegaPath
* Shelby Broadband
* Silica Broadband
* Time Warner
* Toast.net
* Us Signal
* Verizon
* Windstream
* XS Media

### Mobile data

* ATT
* Boost Mobile
* Cricket Wireless
* Sprint
* T-Mobile
* US Cellular
* Verizon
* Other

**Comment by bishoplafer** [comment] 2019-04-30 16:34
```
'XS Media' => 'broadband',
              'Emeral Broadband' => 'broadband',
              'Peak Internet' => 'broadband',
              'Wave' => 'broadband',
              'Douglas Fast Net' => 'broadband',
              'Century Link' => 'broadband',
              'Xfinity' => 'broadband',
              'Viasat' => 'broadband',
              'InfoStructure' => 'broadband',
              'Allstream' => 'broadband',
              'King Street Wireless' => 'broadband',
              'UnwiredWest' => 'broadband',
              'Freewire' => 'broadband',
              'Integra' => 'broadband',
              'Zayo Group' => 'broadband',
              'Lightspeed Networks' => 'broadband',
              'GTT Communications' => 'broadband',
              'Hunter Communications' => 'both',
              'Earthlink' => 'broadband',
              'Windstream' => 'broadband',
              'Spectrocel' => 'broadband',
              'Wave Broadband' => 'broadband',
              'Verizon' => 'broadband',
              'XO' => 'broadband',
              "Comcast" => "broadband",
              "Frontier Communications Corporation" => "broadband",
              "DirectLink" => "broadband",
              "Cascade Utilities" => "broadband",
              "Beavercreek Cooperative Telephone Company" => "broadband",
              "Cleer Creek Communications" => "broadband",
              "Molalla Communications Company" => "broadband",
              "OnlineNW" => "broadband",
              "Colton Telephone Company" => "broadband",
              "Monitor Cooperative Telephone Company" => "broadband",
              "StephouseNetworks" => "broadband",
              "Blackfoot Communications, Inc." => "broadband",
              "St Paul Coop Telephone Assoc" => "broadband",
              "AT_T_Mobility" => "wireless",
              "Verizon Wireless" => "wireless",
              "United_States_Cellular_Corporation" => "wireless",
              'T-Mobile' => 'wireless',
              'Sprint' => 'wireless',
              'Cricket Wireless' => 'wireless',
              'Boost Mobile' => 'wireless',
              'US Cellular' => 'wireless',
              'Other' => 'wireless',
```

**Comment by benanamen** [comment] 2019-04-30 16:37
> I'll also alphabetize the lists, since I don't see any logic to the order currently.

If you are referring to the order the names appear in the selection or the DB, there is no need to alphabetize the list. A simple ORDER BY where ever/how ever the data is called is all you need. I say where ever because I am still reading/learning the code base.

**Comment by noahbrenner** [comment] 2019-04-30 16:40
@bishoplafer Wow, are all of those available in Lane County? Cool, I haven't heard of a lot of them!

@benanamen Currently, their order in the Take the Test form is hard coded in `/app/helpers/home_helper.rb`, as you mentioned, rather than queried from the DB (this should be changed eventually, but I'm thinking we'll save that for the re-write).

**Comment by ryanrolds** [comment] 2019-04-30 16:49
It looks like the seeds haven't been run. That's probably my fault. Try `docker-compose exec frontend rake db:seeds` and check if it populates your local DBs provider_stastics table.

**Comment by noahbrenner** [comment] 2019-04-30 17:08
I think we might be talking about slightly different things and missing each other.

* The `/all-results` page, which shows the map, is populated from a DB query. That _is_ showing up for me, including ISPs and areas on the maps.
* The list in the survey on the home page (via "Take the Test!!" -> "Residential" -> "Let's do this!" -> "Who is your provider?") is hard-coded in `/app/helpers/home_helper.rb`. I've verified this by changing the order and the entries in that file and seeing them reflected on the survey page. **My current question is about the list on this page, since it's the one that's hard-coded.**

**Comment by benanamen** [comment] 2019-04-30 18:03
And herein is exactly why I said "There is a lot of duplicate data that is going to cause confusion during Dev". 

It would be a good idea to make it a priority to get rid of the static provider list and update it to pull from the DB. The Database is the foundation of this whole application. That needs to get dialed in.

**Comment by noahbrenner** [comment] 2019-04-30 18:32
I absolutely agree on the duplicate data! That said, removing may also may be a larger project, depending on how we implement it. For example, I'd prefer defaulting to showing only those providers local to the user taking the test rather than showing them the whole huge list to scroll through, especially as we scale up to the whole country and include lots of little, local ISPs. My current thought is to do the ugly hard-coded thing for now (specifically, June 7th) and then move to sourcing it from the DB when we re-write the frontend (hopefully very soon!).

My current understanding is that the DB doesn't contain info about the areas that each provider is available, making it impossible to query that at this point, but I'd love to be wrong on that. Do we have that information in the DB already?

**Comment by benanamen** [comment] 2019-04-30 18:37
I am on a fast track reading/learning the code so I will be able to give you more and better answers as the hours pass by. I understand the project has a date to work by so some things are probably best left as is for now for that reason. Just what are the specifics the need to be met by the 7th?

**Comment by noahbrenner** [comment] 2019-04-30 19:23
Cool, thanks for doing that research! We're still working on defining the specifics of what we need to do by 6/7. I think Ryan and Asher particularly are working on that, and I expect we'll talk about it when we meet on Thursday.

**Comment by benanamen** [comment] 2019-04-30 19:52
Added new issue with fixes to eliminate static providers list and pull from DB. Topic not related to this Issues thread.

https://github.com/Hack4Eugene/SpeedUpAmerica/issues/52

**Comment by Amcclennahan** [comment] 2019-05-01 01:16
Alright, I'm catching up here. 

Given the wall of text above, it sounds like a new ticket is needed as "Add comcast and century link" doesn't feel representative of the issue. 

Can someone help me there? Do we need an investigative ticket?

**Comment by benanamen** [comment] 2019-05-01 01:41
My Suggestion, implement #52, Update the the DB and close this issue and #52.

**Comment by csjoblom** [comment] 2019-05-01 22:55
@benanamen is #52 actually implemented or did you just change the interaction on the backend? We don't want breakage and should probably do both in tandem just in case the frontend has additional needs.
@Amcclennahan this isn't specific to Comcast and Centurylink at this point, it was during the hackathon as we wanted that as part of the demo.

**Comment by benanamen** [comment] 2019-05-01 23:07
I havent touched a thing on the repo. All I did was post what was needed for the change.

**Comment by noahbrenner** [comment] 2019-05-01 23:11
If folks want it, I'm happy to do a quick PR to add some ISPs to the hard-coded list, but I think @benanamen is right that a DB-based solution would be better. I don't think we need to do both.

Oh, and it looks like you're assigned to that ticket now!

**Comment by benanamen** [comment] 2019-05-01 23:45
An FYI on the hard coded providers: There is a conditional of showing only certain providers if it is on "first_step" which is the difference between choosing "Residential" or "Mobile Data" on the testing checkbox options. I wasn't going to implement #52 until I did the conditional in ActiveRecord. If in your current deadline it doesn't matter that only mobile providers show in the drop down for the "Mobile data" selection then #52 could be implemented now allowing for a single source of truth for provider names which will eliminate the double duty of dealing with provider names.

I am hesitant on this non essential update in that it is all going to have to be redone at some point most likely after your deadline date because the DB design is wrong which means any changes based on the current DB will all have to be redone/fixed when the DB is corrected. That, and that this team will likely choose an alternate development platform for this application. I posted the changes needed to pull from the DB. It's up to you guys if it really matters right now. Worst case is that someone has to update the DB and the static list for provider changes. As long as that is a known, it is not really that big of a deal. By now I assume it is known who the providers are for Lane County, so the double update should really only have to be done once for now.

**Comment by csjoblom** [comment] 2019-05-02 15:27
I would guess we would bare minimum like Eugene ISPs for the June 7th demo
@ryanrolds @Amcclennahan @mattsayre may be able to speak to that better than I.

**Comment by Amcclennahan** [comment] 2019-05-02 17:54
Yep, at a bare minimum we want an accurate list of the Eugene ISP's, @csjoblom is right on the money there.

**Comment by ryanrolds** [comment] 2019-05-02 19:13
In the long run we will need to get ISP info from NDT as a state-level or national-level searchable list of ISP will be a pain to maintain.

**Comment by noahbrenner** [comment] 2019-05-02 19:33
@Amcclennahan For now, is there a good place to find such a canonical list for Eugene so we can get a temporary fix pushed?

@ryanrolds Agreed that we definitely don't want to maintain that list manually in the long run.

**Comment by ryanrolds** [comment] 2019-05-02 19:39
https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/db/seeds.rb#L10

**Comment by ryanrolds** [comment] 2019-05-02 19:41
A good ticket for this would say:

The "Residential" and "Mobile" speed test paths require users to select their ISP. Currently, the list is populated from a static list (`app/helpers/home_helper.rb#L5`). We want them to come from the `provider_statistics` table in the DB. 

* Get the providers loaded using `rake db:seed` and update setup instructions to run seed.
* Update lists in speed test form to come from `provider_statistics` table.
* Make sure the ISP filter on the map also is coming from the table

**Comment by ryanrolds** [comment] 2019-05-02 21:17
Updating the UI is a duplicate of https://github.com/Hack4Eugene/SpeedUpAmerica/issues/52, which is assigned to Kevin right now.

**Comment by benanamen** [comment] 2019-05-02 22:44
Kevin (me) will handle #52 after the meetup tonight.

**Comment by nohorse** [comment] 2019-05-06 16:00
I just tested from my house in Sherwood (outside of lane county) and Frontier was not on the list.  Maybe not a huge deal, but they are a FIOS reseller I think 
![image](https://user-images.githubusercontent.com/311063/57238074-6be2ec00-6fdd-11e9-89ac-7b31b3791651.png)

**Comment by benanamen** [comment] 2019-05-06 16:05
@nohorse , That particular drop down select is populated from a hard coded file. We have an issue open to pull provider names from the database. When you ran a speed test your provider should have been added to the DB and should now be visible in the drop down select on the all-result map page. Can you please verify if you see it there or not.

**Comment by nohorse** [comment] 2019-05-06 16:26
I see it there!  thanks!

**Closed** 2019-05-08 04:46 UTC
Labels: urgent
