### ISSUE TITLE
Investigate and fix Safari geolocation error (0.5SP)

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#110] opened 2019-06-08 21:55 UTC
Issue reported by Chris S, https://hack4cause.slack.com/archives/CHCMW8URJ/p1559929761016000

**Comment by antonioortegajr** [comment] 2019-06-09 22:00
Unable to reproduce. 
OSX 10.14.5
also iOS 12.3.1

Is worth noting that if you do not allow the geo location the site does still let you continue as if you could initiate the test. Then fails silently.

**Comment by ryanrolds** [comment] 2019-06-09 22:29
@antonioortegajr What versions of Safari? 
@csjoblom What version of OSX and Safari? Any errors in the console?

Let's include fixing the lack of blocking reported by Antonio in this ticket. Also, check IE and Firefox.

**Comment by antonioortegajr** [comment] 2019-06-09 22:43
OSX 10.14.5 Safari 12.1.1 updated comment above.

**Comment by ryanrolds** [comment] 2019-06-13 14:53
I will give anyone wanting to work on this temporary access to my BrowserStack account.

**Comment by csjoblom** [comment] 2019-06-13 16:52
My iMac is running: 
OSX 10.14.6 Beta
Safari is 12.1.2

My macbook pro is running:
OSX 10.14.5
Safari is 12.1.1

Macbook now runs the test correctly, iMac does not. No console errors. Looks like this could be related to beta version of Safari, but may be an issue once it's fully released.

**Comment by ryanrolds** [comment] 2019-06-13 20:28
Interesting. Thank for clarifying the affected machine is a beta version of Safari. This is why we include browser versions. :)

https://imgur.com/gallery/0Na7qvJ

**Comment by csjoblom** [comment] 2019-06-13 20:51
Macbook pro is now on 10.4.6 Beta 2
Safari 12.1.2

Can't reproduce, going to assume it's the imac and not a general issue. We can reopen if others report.

**Comment by csjoblom** [comment] 2019-06-13 21:52
Reopening: looks like there is an issue when geolocation is available but it can't get a location.

https://files.slack.com/files-pri/T40B5U6PL-FK7AS0VJ6/image.png

Note that I do have Location Services enabled in OSX for Safari.

**Comment by csjoblom** [comment] 2019-06-13 22:18
So @ryanrolds was able to track down why this was happening. If you have wifi turned off (even if you are using ethernet) geolocation will not return a location in Safari. 

We will still need to handle for this scenario, thanks Apple.

**Comment by ryanrolds** [comment] 2019-06-14 23:23
The fix for this would check specifically for the `POSITION_UNAVAILABLE ` error and showing a message to the users to turn on WiFi.

**Comment by ryanrolds** [comment] 2019-06-29 17:02
I started collecting the specific PositionError codes and messages in Sentry.io. We see a lot of errors about users blocking access to user location. We need to rethink how and when we prompt people. We also may need to consider falling back to IP based geocoding.

**Comment by Kourchenko** [comment] 2019-07-17 23:39
Issue addressed. Issue occurs when WiFi is not enabled.
7/17 - Issue fixed by informing the user to turn on WiFi and enable Location Services.

**Closed** 2019-07-18 23:54 UTC
Labels: bug, good first issue, help wanted
